# PyMotions
## Giulia Passarelli, Hélio Paiva Neto, Warlen Rodrigues
### Projeto 3 de Robótica

### Pegando a base de dados e realizando a conta para os cinco ângulos faciais:

In [1]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.multiclass import OneVsRestClassifier
from sklearn.naive_bayes import GaussianNB

dados = pd.read_csv("data\Treinamento.csv", sep=";")

dados.sort_values(by=['image'])

#0=Neutro; 1=Feliz; 2=Triste

,image,face_x,face_y,face_width,face_height,x0,y0,x1,y1,x2,...,y63,x64,y64,x65,y65,x66,y66,x67,y67,Categoria
0,data-20180522-171958.png,242,201,186,186,253,274,256,297,260,...,344,369,346,356,345,347,347,338,346,0
1,data-20180522-172005.png,241,167,223,223,254,236,256,261,259,...,314,392,310,369,328,355,331,340,330,1
2,data-20180522-172008.png,241,167,223,223,251,246,256,273,262,...,327,383,333,367,328,356,329,344,328,2
3,data-20180522-172012.png,241,167,223,223,258,239,260,265,264,...,326,385,326,370,329,360,331,351,329,0
4,data-20180522-172015.png,242,201,186,186,243,248,247,274,254,...,339,376,336,357,342,348,344,339,343,0
5,data-20180522-172016.png,242,180,186,186,246,242,250,269,255,...,330,374,337,361,350,352,352,344,351,2

In [2]:
ang1=[]
ang2=[]
ang3=[]
ang4=[]
ang5=[]

for index,row in dados.iterrows():
    
    #ANGULO 1
    vec1_1 = np.array([row['x63']-row['x48'], row['y63']-row['y48']])
    vec1_2 = np.array([row['x67']-row['x48'], row['y67']-row['y48']])
    angulo1 = np.math.atan2(np.linalg.det([vec1_1,vec1_2]),np.dot(vec1_1,vec1_2))
    ang1.append(angulo1)
    
    #ANGULO 2
    vec2_1 = np.array([row['x33']-row['x48'], row['y62']-row['y48']])
    vec2_2 = vec1_1
    angulo2 = np.math.atan2(np.linalg.det([vec2_1,vec2_2]),np.dot(vec2_1,vec2_2))
    ang2.append(angulo2)
    
    #ANGULO 3
    vec3_1 = np.array([row['x31']-row['x48'], row['y31']-row['y48']])
    vec3_2 = np.array([row['x54']-row['x48'], row['y54']-row['y48']])
    angulo3 = np.math.atan2(np.linalg.det([vec3_1,vec3_2]),np.dot(vec3_1,vec3_2))
    ang3.append(angulo3)
    
    #ANGULO 4
    vec4_1 = np.array([row['x54']-row['x57'], row['y54']-row['y57']])
    vec4_2 = np.array([row['x48']-row['x57'], row['y48']-row['y57']])
    angulo4 = np.math.atan2(np.linalg.det([vec4_1,vec4_2]),np.dot(vec4_1,vec4_2))
    ang4.append(angulo4)
    
    #ANGULO 5
    vec5_1 = np.array([row['x31']-row['x51'], row['y31']-row['y51']])
    vec5_2 = np.array([row['x35']-row['x51'], row['y35']-row['y51']])
    angulo5 = np.math.atan2(np.linalg.det([vec5_1,vec5_2]),np.dot(vec5_1,vec5_2))
    ang5.append(angulo5)
    
dados['angulo1'] = pd.Series(ang1)
dados['angulo2'] = pd.Series(ang2)
dados['angulo3'] = pd.Series(ang3)
dados['angulo4'] = pd.Series(ang4)
dados['angulo5'] = pd.Series(ang5)    

#ang1 - 63,49,66
#ang2 - 34,49,63
#ang3 - 32,49,55
#ang4 - 55,58,49
#ang5 - 32,52,36

In [3]:
dados.to_csv("data\imagens_com_angulos.csv")

In [4]:
X = dados.loc[:, ("angulo1", "angulo2", "angulo3", "angulo4", "angulo5")]
y = dados.loc[:, ("Categoria")]

In [6]:
clf = OneVsRestClassifier(GaussianNB(priors=None)).fit(X, y)

In [7]:
clf.predict(#Angulos Do Teste)

array([0, 1, 2, 0, 0, 2], dtype=int64)